#!/bin/zsh
# Build a release binary and assemble the Halo.app bundle.
#
#   ./package.sh
#
# The ring is read-only, but focus-shake (`shake = true`) MOVES the
# focused window via AX, which needs the Accessibility (TCC) grant.
# TCC keys that grant to the code-signing identity, so to keep it
# across the rebuild-heavy dev loop, run ./setup-signing-cert.sh once
# (it writes a stable identity name to .signing-id, used below).
# Without it you fall back to ad-hoc and re-grant every relaunch.
# CI / brew pass CODESIGN_ID="-".
#
# The bundle id is com.halo.app — keep it stable across versions.
set -e
cd "$(dirname "$0")"

APP="Halo.app"

swift build -c release

# Clean up any prior bundle before re-assembling.
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp Info.plist "$APP/Contents/Info.plist"
cp .build/release/halo "$APP/Contents/MacOS/halo"   # = CFBundleExecutable

# Stamp the bundle's marketing version from git so the displayed
# version is accurate (the committed Info.plist value is only a
# fallback for a tag-less tarball build). `git describe` → e.g.
# v1.0.0-3-g1e77545 → 1.0.0-3-g1e77545; a clean tagged build is just
# 1.0.0.
VERSION="$(git describe --tags --dirty 2>/dev/null | sed 's/^v//')"
if [[ -n "$VERSION" ]]; then
  /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" \
    "$APP/Contents/Info.plist" >/dev/null 2>&1 || true
fi

# App icon: AppIcon.icns is generated by scripts/build-icon.sh and
# committed to the repo (regenerate when the symbol / palette
# changes). Referenced by Info.plist's CFBundleIconFile = AppIcon.
if [[ -f AppIcon.icns ]]; then
  cp AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"
fi

# Identity precedence: $CODESIGN_ID > .signing-id file > ad-hoc ("-").
# Hybrid (best-effort cert, loud fallback): try the stable identity, but
# if codesign can't use the keychain key (errSecInternalComponent —
# locked keychain, ACL refusal, broken cert), fall back to ad-hoc with a
# warning instead of aborting. Ad-hoc works fine; the only cost is the
# AX grant dropping when the binary changes (not on config-only tweaks).
ID="${CODESIGN_ID:-}"
if [[ -z "$ID" && -f .signing-id ]]; then ID="$(cat .signing-id)"; fi
ID="${ID:--}"
if ! codesign --force --sign "$ID" "$APP" 2>/tmp/halo-codesign.err; then
  if [[ "$ID" != "-" ]]; then
    echo "warning: signing with \"$ID\" failed ($(tr -d '\n' </tmp/halo-codesign.err)) — ad-hoc fallback" >&2
    echo "  (fix later: ./setup-signing-cert.sh + click 'Always Allow', or just use ad-hoc)" >&2
    ID="-"
    codesign --force --sign - "$APP"
  else
    echo "codesign (ad-hoc) failed:" >&2; cat /tmp/halo-codesign.err >&2; exit 1
  fi
fi

echo "built $APP  (signed: $ID)"
echo "launch: open $APP   |   quit: ./stop.sh"
