#!/bin/zsh
# Build a release binary and assemble the Halo.app bundle.
#
#   ./package.sh
#
# halo touches NO TCC-gated APIs (no Accessibility / no Screen
# Recording — just AppKit + read-only private SkyLight), so unlike
# facet there is no self-signed-cert dance and no dev/release bundle
# split: there's no grant to keep stable across rebuilds. Plain
# ad-hoc signing is enough. (Override the identity with CODESIGN_ID
# if you ever want a real one; CI passes CODESIGN_ID="-".)
#
# The bundle id is com.halo.app — keep it stable across versions.
set -e
cd "$(dirname "$0")"

APP="Halo.app"

swift build -c release

# Clean up any prior bundle before re-assembling.
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp Info.plist "$APP/Contents/Info.plist"
cp .build/release/halo "$APP/Contents/MacOS/halo"   # = CFBundleExecutable

# Stamp the bundle's marketing version from git so the displayed
# version is accurate (the committed Info.plist value is only a
# fallback for a tag-less tarball build). `git describe` → e.g.
# v1.0.0-3-g1e77545 → 1.0.0-3-g1e77545; a clean tagged build is just
# 1.0.0.
VERSION="$(git describe --tags --dirty 2>/dev/null | sed 's/^v//')"
if [[ -n "$VERSION" ]]; then
  /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" \
    "$APP/Contents/Info.plist" >/dev/null 2>&1 || true
fi

# App icon: AppIcon.icns is generated by scripts/build-icon.sh and
# committed to the repo (regenerate when the symbol / palette
# changes). Referenced by Info.plist's CFBundleIconFile = AppIcon.
if [[ -f AppIcon.icns ]]; then
  cp AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"
fi

# Identity precedence: $CODESIGN_ID > ad-hoc ("-").
ID="${CODESIGN_ID:--}"
codesign --force --sign "$ID" "$APP"

echo "built $APP  (signed: $ID)"
echo "launch: open $APP   |   quit: ./stop.sh"
